version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: cultural_events
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    build:
      context: .
    container_name: springboot-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cultural_events
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./application.properties:/app/application.properties:ro

volumes:
  mysql_data:
